services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Aa1234
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: dbpasword_1
    networks:
      - books-net
    volumes:
      - mysql-volume:/var/lib/mysql

  bookstore:
    image: bookstoreapi:latest
    networks:
      - books-net
    ports:
      - "80:80"
    depends_on:
      - database
    restart: always

networks:
  books-net:

volumes:
  mysql-volume: